inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
  - db/schema.rb
  - db/migrate/*
  - config/application.rb
  - "**/config.ru"
  - bin/*
  - vendor/bundle/**/*
  TargetRubyVersion: 3.0.0
